#=========================port===============================================
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

#====Decided the configuration file through mvn packaged -P/-- params=============
spring:
  datasource:
    username: dyp
    password: 1234567890
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase/master.xml
    #    contexts: local,test,prod
    contexts: local
    enabled: true
  mvc:
    view:
      prefix: classpath:templates/
      suffix: .html
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache-local.xml
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
#  thymeleaf:
#    mode: LEGACYHTML5
#    encodeing: UTF-8
#    content-type: text/html
#    prefix: classpath:templates/
#    suffix: .html
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
#====================log configuration===============================================
logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework: INFO
    com:
      tra: DEBUG


#===================self configuration===============================================

adminPath: /admin

frontPath: /f

urlSuffix: .html

systemName: CMSManager
